# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160923021937 on 2016-10-24 01:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 10, 24, 1, 5, 14, 173549, tzinfo=utc))),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cat', models.ManyToManyField(related_name='fitnessEquipment_cat', to='fitness.FitnessCategories')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessSubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitnessSubCat_child', to='fitness.FitnessCategories')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitnessSubCat_parent', to='fitness.FitnessCategories')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Video Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Published on')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated On')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitnessVideo_category', to='fitness.FitnessCategories')),
            ],
        ),
        migrations.CreateModel(
            name='FoodClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('energy', models.DecimalField(decimal_places=3, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=3, max_digits=6)),
                ('saturated_fat', models.DecimalField(decimal_places=3, max_digits=6)),
                ('polyunsaturated_fat', models.DecimalField(decimal_places=3, max_digits=6)),
                ('monounsaturated_fat', models.DecimalField(decimal_places=3, max_digits=6)),
                ('trans_fat', models.DecimalField(decimal_places=3, max_digits=6)),
                ('gluten', models.BooleanField(default=False)),
                ('cholesterol', models.DecimalField(decimal_places=3, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=3, max_digits=6)),
                ('classes', models.ManyToManyField(related_name='foodDetail_class', to='fitness.FoodClasses')),
            ],
        ),
        migrations.CreateModel(
            name='FoodSubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodSubClass_child', to='fitness.FoodClasses')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodSubClass_parent', to='fitness.FoodClasses')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('amount_units', models.CharField(max_length=5)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_food', to='fitness.FoodDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('ingredients', models.ManyToManyField(related_name='recipe_ingredients', to='fitness.Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
                ('email_verified', models.BooleanField(default=False)),
                ('secure_token', models.CharField(blank=True, max_length=50, null=True)),
                ('forgotten_token', models.CharField(blank=True, max_length=50, null=True)),
                ('forgotten_token_created', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_location_lat', models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=10, null=True)),
                ('last_location_long', models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=10, null=True)),
                ('user_avatar_dir', models.CharField(blank=True, default='/img/avatar1.jpg', max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('blood_pressure_systolic', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure_diastolic', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('athlete', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('medical_implant', models.BooleanField(default=False)),
                ('attendence', models.IntegerField(default=0)),
                ('last_attend_date', models.CharField(blank=True, max_length=30, null=True)),
                ('training_target', models.CharField(blank=True, max_length=20, null=True)),
                ('classification', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideosReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=50, null=True)),
                ('review', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.UserAccounts')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.FitnessVideo')),
            ],
        ),
        migrations.AddField(
            model_name='friendslist',
            name='friend1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendList_1', to='fitness.UserAccounts'),
        ),
        migrations.AddField(
            model_name='friendslist',
            name='friend2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendList_2', to='fitness.UserAccounts'),
        ),
        migrations.AddField(
            model_name='fitnessvideo',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitnessVideo_uploadedBy', to='fitness.UserAccounts'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatting_user', to='fitness.UserAccounts'),
        ),
    ]
